### ISSUE TITLE
rocminfo segfaults and makes the kernel instable afterwards with an X570 board with F11 BIOS, AMD Radeon VII GPU

### ISSUE THREAD

**Issue by DarjanKrijan** [ROCm/rocminfo#30]
Will leave my Arch Linux forum post here as it has all the details:
https://bbs.archlinux.org/viewtopic.php?pid=1888283#p1888283

**Comment by darjankrijan** [comment]
So, long story short, for some reason the rocminfo utility segfaults with an updated BIOS + recent kernel (5.5.2...5.5.5) on this board (works and prints info with the default F1 BIOS).

And when it segfaults it takes the whole system down with kernel panics.

rocminfo works on kernels 5.3.0 (Ubuntu 18.04) and 5.4.21 (Arch Linux's LTS kernel) with this updated BIOS though.

**Comment by ppanchad-amd** [comment]
@DarjanKrijan Apologies for the lack of response. Do you still need assistance with this issue? If not, please close the ticket. Thanks!
