### ISSUE TITLE
Newer kernels restrict /dev/kdf to members of the 'render' group

### ISSUE THREAD

**Issue by braiam** [ROCm/rocminfo#34]
I'm unsure since when, but on my system the /dev/kdf file was restricted to root:render, but rocminfo only checks for video. Maybe it should check which group the device is attached to and use that instead of testing against static video. Also, it would be preferable to catch EACCESS errors and return them as permission denied operations, rather than `HSA_STATUS_ERROR_OUT_OF_RESOURCES`

**Comment by ppanchad-amd** [comment]
@braiam Apologies for the lack of response. Do you still need assistance with this issue? If not, please close the ticket. Thanks!

**Comment by ppanchad-amd** [comment]
@braiam Closing ticket. Please re-open the ticket if you still see the issue with the latest ROCm. Thanks!
