### ISSUE TITLE
Debian / Ubuntu 3.5.1 package does not install libhsakmt.so.1

### ISSUE THREAD

**Issue by Dantali0n** [ROCm/rocminfo#35]
The 3.5.1 Packages for Debian and Update do not install `libhsakmt.so.1` in `/opt/rocm/rocm-3.5.1/lib`.

The install of rocminfo is no broken leading to:
```
/opt/rocm/bin/rocminfo: error while loading shared libraries: libhsakmt.so.1: cannot open shared object file: No such file or directory
```

**Comment by ppanchad-amd** [comment]
@Dantali0n Apologies for the lack of response.  Can you please check if your issue still exists with the latest ROCm 6.2? If not, please close the ticket. Thanks!
