### ISSUE TITLE
Can't retrieve username through getlogin_r

### ISSUE THREAD

**Issue by haampie** [ROCm/rocminfo#39]
When using Slurm it seems like `getlogin_r` is not a reliable way to get the current user's username. I'm getting this error:

```
ROCk module is loaded
Unable to open /dev/kfd read-write: Operation not permitted
Failed to get user name to check for video group membership
```

The latter fails generally on that node, e.g.:

```c
$ cat main.c 
#include <pwd.h>
#include <unistd.h>
#include <stdio.h>

int main() {
    // Get username through getlogin_r
    char u_name[32];
    int result = getlogin_r(u_name, 32);

    if (result)
      printf("Error getting username through getlogin_r. Code = %d\n", result);
    else
      printf("Got username through getlogin_r: %s\n", u_name);

    // Get username through getpwuid(getuid)
    struct passwd *pwd = getpwuid(getuid());
    if (pwd)
      printf("Got username through getpwuid(getuid()): %s\n", pwd->pw_name);
    else
      printf("Error getting username through getpwuid(getuid())\n");
}

$ gcc main.c 
$ ./a.out 
Error getting username through getlogin_r. Code = 6
Got username through getpwuid(getuid()): harmen
```

Maybe `getlogin_r` should be replaced with getuid here: https://github.com/RadeonOpenCompute/rocminfo/blob/master/rocminfo.cc#L1091

In any case, it's a bit annoying to get this error, since it's an error when trying to handle the original error.

**Comment by cfreehill** [comment]
Hi, 
Looking at the man-page for getlogin_r, it looks like that error is returned when "The calling process has no controlling terminal." I assume this means it is run from, for example, a daemon. Is that the case?
The solution you propose looks reasonable, and you were able to demonstrate the problem and fix with the a.out program, but I'm wondering if you would be able to test it as slurm is using it? Can you easily make the change in rocminfo, build and test it? I can build it and run it, but I don't have your environment to test it. Or, when I get a chance, I can make the change on my fork, for you to build/test.

**Comment by ppanchad-amd** [comment]
@haampie Is this ticket still relevant? If not, please close the ticket. Thanks!

**Comment by ppanchad-amd** [comment]
@haampie Closing ticket. Please re-open if you still see the issue with the latest ROCm and we will investigate further. Thanks!
