### ISSUE TITLE
cross-compilation fixup

### ISSUE THREAD

**Issue by emollier** [ROCm/rocminfo#60]
Hi,

Helmut Grohne noticed in [Debian Bug#1024611](https://bugs.debian.org/1024611) that crossbuild attempts of rocminfo were choking on x86_64 specific flags.  Indeed, I observe the following when attempting a cross-compilation of rocminfo 5.2.3 to target for instance aarch64 hosts:

```
[ 50%] Building CXX object CMakeFiles/rocminfo.dir/rocminfo.cc.o
/usr/bin/aarch64-linux-gnu-g++ -DDEBUG -DLITTLEENDIAN_CPU=1 -D__linux__ -isystem /usr/include/hsa -g -O2 -ffile-prefix-map=/<<PKGBUILDDIR>>=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g -std=c++11 -fexceptions -fno-rtti -fno-math-errno -fno-threadsafe-statics -fmerge-all-constants -fms-extensions -Werror -Wall -m64 -msse -msse2 -ggdb -O0 -MD -MT CMakeFiles/rocminfo.dir/rocminfo.cc.o -MF CMakeFiles/rocminfo.dir/rocminfo.cc.o.d -o CMakeFiles/rocminfo.dir/rocminfo.cc.o -c /<<PKGBUILDDIR>>/rocminfo.cc
aarch64-linux-gnu-g++: error: unrecognized command-line option ‘-m64’
aarch64-linux-gnu-g++: error: unrecognized command-line option ‘-msse’
aarch64-linux-gnu-g++: error: unrecognized command-line option ‘-msse2’
make[3]: *** [CMakeFiles/rocminfo.dir/build.make:79: CMakeFiles/rocminfo.dir/rocminfo.cc.o] Error 1
```

The original patch addresses the presence of sse extensions flags, but some hosts still choke on the -m64.  I could get the build to go through removing the -m64 entirely (perhaps it might be better to move it within the check):

```patch
--- rocminfo.orig/CMakeLists.txt
+++ rocminfo/CMakeLists.txt
@@ -138,12 +138,12 @@
 set(ROCMINFO_CXX_FLAGS ${ROCMINFO_CXX_FLAGS} -fms-extensions)
 set(ROCMINFO_CXX_FLAGS ${ROCMINFO_CXX_FLAGS} -Werror)
 set(ROCMINFO_CXX_FLAGS ${ROCMINFO_CXX_FLAGS} -Wall)
-set(ROCMINFO_CXX_FLAGS ${ROCMINFO_CXX_FLAGS} -m64)
+#set(ROCMINFO_CXX_FLAGS ${ROCMINFO_CXX_FLAGS} -m64)
 
 #
 # Extend the compiler flags for 64-bit builds
 #
-if((${CMAKE_HOST_SYSTEM_PROCESSOR} STREQUAL "x86_64") OR (${CMAKE_HOST_SYSTEM_PROCESSOR} STREQUAL "AMD64"))
+if((${CMAKE_SYSTEM_PROCESSOR} STREQUAL "x86_64") OR (${CMAKE_SYSTEM_PROCESSOR} STREQUAL "AMD64"))
   set(ROCMINFO_CXX_FLAGS ${ROCMINFO_CXX_FLAGS} -msse -msse2)
 endif()
 
```

We mostly worked with rocminfo version 5.2.3, but looking at the master branch, I would expect this bug to still be present up to 5.3.3.  The cmake version is 3.25.0 in case it were to be relevant.

In hope cross-compilation is of interest,
Have a nice day,  :)
Étienne.

**Comment by ppanchad-amd** [comment]
@emollier Apologies for the lack of response.  Can you please check if your issue still exists with the latest ROCm 6.2? If not, please close the ticket. Thanks!

**Comment by emollier** [comment]
As far as I can see from the latext CMakeLists.txt, the initial problem is actionned and should now be resolved.  If I'm hitting other cross compilation problems, they would be related to different code segments that could have changed in the meantime.  I would tend to consider them a different problem at this point and would come back to you with a new issue if/when I run into them.

So... _drumrolls_... I close this entry.  :)
