### ISSUE TITLE
rocminfo giving wrong gpu name in docker

### ISSUE THREAD

**Issue by bghimireamd** [ROCm/rocminfo#61]
I ran a docker container rocm/miopen:ci (rocm5.3) on Navi31. The docker then tells me that it is gfx1030 (Navi 21) which, clearly is not because the metal is Navi 31. I wished it would have errored with proper error message instead of silently giving wrong GPU name. Error message example : "rocm version mismatch",  

Detail : 
rocm version :  5.3 
metal GPU     : Navi31
docker GPU   : Navi21 // should have give error instead of wrong GPU name

steps to reproduce : 

1. docker run -it --rm --network=host --ipc=host --device=/dev/kfd --device=/dev/dri --group-add video --cap-add=SYS_PTRACE --security-opt seccomp=unconfined -v /home/fpadmin/bghimire:/root/ --name miopen_test  rocm/miopen:ci 
2. docker exec -it miopen_test  bash 
3. rocminfo | grep gfx

Name:                    gfx1030

**Comment by ppanchad-amd** [comment]
@bghimireamd Can you please check if this still exists with the latest ROCm 6.2? If not, please close the ticket. Thanks!

**Comment by bghimireamd** [comment]
I see correct gfx in 6.2
